openapi: 3.0.0
info:
  title: Flask ML API
  version: 0.1.1
  description: API for processing machine learning inputs and returning results.
paths: {}
components:
  schemas:
    MLInput:
      type: object
      description: Base model for ML input data.

    TextInput:
      allOf:
        - $ref: '#/components/schemas/MLInput'
        - type: object
          required: 
            - text
          properties:
            text:
              type: string
              description: Text to be processed
              minLength: 1

    FileInput:
      allOf:
        - $ref: '#/components/schemas/MLInput'
        - type: object
          required: 
            - file_path
          properties:
            file_path:
              type: string
              description: Path of the file to be processed
              minLength: 1

    CustomInput:
      allOf:
        - $ref: '#/components/schemas/MLInput'
        - type: object
          required: 
            - input
          properties:
            input:
              description: Custom input data
              default: {}
              anyOf:
                - type: string
                - type: number
                - type: boolean
                - type: array
                - type: object

    RequestModelGenerated:
      type: object
      properties:
        inputs:
          type: array
          description: List of input items to be processed
          items:
            oneOf:
              - $ref: '#/components/schemas/TextInput'
              - $ref: '#/components/schemas/FileInput'
              - $ref: '#/components/schemas/CustomInput'
          minLength: 1
        data_type:
          $ref: '#/components/schemas/DataTypes'
        parameters:
          type: object
          description: Additional parameters for the ML model
          default: {}
      required:
        - inputs
        - data_type
      description: |
        Represents a request model for processing inputs with an ML model.
        - Validates data_type must be one of TEXT, IMAGE, VIDEO, AUDIO, or CUSTOM.
        - Validates inputs to match the data_type.

    MLResult:
      type: object
      required: 
        - id
      description: Base model for ML result data.
      properties:
        id:
          type: string
          description: The ID of the result
          minLength: 1

    FileResult:
      allOf:
        - $ref: '#/components/schemas/MLResult'
        - type: object
          required: 
            - result
            - file_type
          properties:
            result:
              type: string
              description: Path of the result file.
              minLength: 1

    ImageResult:
      allOf:
        - $ref: '#/components/schemas/FileResult'

    VideoResult:
      allOf:
        - $ref: '#/components/schemas/FileResult'

    AudioResult:
      allOf:
        - $ref: '#/components/schemas/FileResult'

    TextResult:
      allOf:
        - $ref: '#/components/schemas/MLResult'
        - type: object
          required:
            - result
          properties:
            result:
              type: string
              description: The result text.
              minLength: 1

    BatchTextResult:
      type: object
      required: 
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/TextResult'
          minLength: 1
          description: List of text results

    BatchImageResult:
      type: object
      required: 
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/ImageResult'
          minLength: 1
          description: List of image results

    BatchVideoResult:
      type: object
      required: 
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/VideoResult'
          minLength: 1
          description: List of video results

    BatchAudioResult:
      type: object
      required: 
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/AudioResult'
          minLength: 1
          description: List of audio results

    BaseResponseModel:
      type: object
      description: Base model for response models.
      properties: {}

    ResponseModel:
      allOf:
        - $ref: '#/components/schemas/BaseResponseModel'
        - type: object
          required:
            - results
          properties:
            status:
              type: string
              description: The status of the operation, e.g., 'SUCCESS'
              minLength: 1
              default: SUCCESS
            results:
              oneOf:
                - $ref: '#/components/schemas/BatchTextResult'
                - $ref: '#/components/schemas/BatchImageResult'
                - $ref: '#/components/schemas/BatchVideoResult'
                - $ref: '#/components/schemas/BatchAudioResult'

    ErrorResponseModel:
      allOf:
        - $ref: '#/components/schemas/BaseResponseModel'
        - type: object
          required:
            - status
            - errors
          properties:
            status:
              type: string
              description: The status of the operation, e.g., 'ERROR'
              minLength: 1
              default: ERROR
            errors:
              type: array
              items:
                anyOf:
                  - type: string
                  - type: object
              description: Details about the error that occurred
    DataTypes:
      type: string
      description: Enum for data types
      enum: ["TEXT", "IMAGE", "VIDEO", "AUDIO", "CUSTOM"]
